const styles = {
  containerCreateButton: {
    width: '60px',
    height: '60px',
    borderRadius: 50,
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    bottom: '15px',
  },
  createButton: {
    width: '60px',
    height: '60px',
    borderRadius: 50,
    position: 'absolute',
    backgroundColor: 'primary.500',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
    elevation: 1,
  },
  createButtonBorderWrapper: {
    width: '80px',
    height: '40px',
    backgroundColor: 'red',
    overflow: 'hidden',
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: -1,
    elevation: -1,
    bottom: '-19px',
  },
  border: {
    width: '72px',
    height: '72px',
    backgroundColor: 'rgba(233, 236, 237, 1)',
    borderRadius: '35px',
    zIndex: -1,
    elevation: -1,
    bottom: '18px',
  },
  icon: {
    w: '48px',
    h: '48px',
    borderRadius: '24px',
    bg: 'primary.200',
    justifyContent: 'center',
    alignItems: 'center',
    mb: '12px',
  },
};
export default styles;
